<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>AcceptPurchaseOrders</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>046cf0c9-4744-4e45-a33c-595d095a59bb</testSuiteGuid>
   <testCaseLink>
      <guid>f1fd34ff-3d18-40b6-8707-fcfbe8ea2b71</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Testcases/01_Login/01_TC01_Test valid credentials</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>e70c892c-c9d3-49e3-a861-f20a50699b12</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/General/SideMenu/OpenPages/Open Purchase Page</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>4bd97f16-1761-45f5-8bef-5c7523fa60b1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/General/Purchase Order/SearchOnPOs</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7bd7a4b2-8506-42b7-810b-edf9bb447ab8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8594f07f-6a90-4f9a-840d-c41a723df909</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bacaa2b9-5642-4432-8c75-bf64258afd1c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Testcases/02_Purchase orders/POs tab/02_TC01 View PO details</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0a12a7fa-2355-44df-98dd-728c254a52dc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0aeef7f8-81a9-4302-b4ab-593ddf4d6c31</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7ee54879-83aa-4693-a119-b27323f8e5ef</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>22724d96-4a03-455b-a42e-a3558c79ea06</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Testcases/02_Purchase orders/POs tab/02_TC02 Accept Purchase order</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e0e66c75-30d9-43e0-bb63-02467213a46c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a845c93-8b9e-4b54-bdf4-b9a3dcb52bcf</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
