<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>RejectPurchaseOrders</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>bf437a2e-5d34-4918-9559-e12c291bee7b</testSuiteGuid>
   <testCaseLink>
      <guid>de03af99-b9ad-450a-95b2-ef94e540149b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Testcases/01_Login/01_TC01_Test valid credentials</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>80eca720-313e-497b-a270-8036d771fad6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/General/SideMenu/OpenPages/Open Purchase Page</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>834733b5-976f-43b2-a9c4-8e21876f981b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/General/Purchase Order/SearchOnPOs</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7bd7a4b2-8506-42b7-810b-edf9bb447ab8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8594f07f-6a90-4f9a-840d-c41a723df909</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d02b0923-7431-4f4a-959c-fb9684648dd4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Testcases/02_Purchase orders/POs tab/02_TC01 View PO details</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0a12a7fa-2355-44df-98dd-728c254a52dc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0aeef7f8-81a9-4302-b4ab-593ddf4d6c31</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7ee54879-83aa-4693-a119-b27323f8e5ef</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e962efaf-7591-4edc-bd85-2cfdb3d67690</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Testcases/02_Purchase orders/POs tab/02_TC03 Reject Purchase order</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>84e794a8-ca6f-4f6f-a1a5-40e85af059da</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2e1c700d-2bcc-4d19-b7d9-30e873a08938</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
