<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BranchesList</name>
   <tag></tag>
   <elementGuidId>2b2865b4-e945-4583-b8f1-1198a3f6c7eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ul.show</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//app-supplier-nav[@id='side-menu']/div/div[2]/div/nav/ul/div/app-custom-dropdown/ul</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ul</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>[object Object]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>show</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Sharq Almadenah - Jubail - Sary  Sharq Almadenah - Dmm - Sary </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;side-menu&quot;)/div[@class=&quot;new-design ng-star-inserted&quot;]/div[@class=&quot;mobile-menu rtl active&quot;]/div[@class=&quot;mobile-menu-widget active&quot;]/nav[@class=&quot;nav&quot;]/ul[1]/div[@class=&quot;dropDown&quot;]/app-custom-dropdown[@class=&quot;branches-dropdown&quot;]/ul[@class=&quot;show&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//app-supplier-nav[@id='side-menu']/div/div[2]/div/nav/ul/div/app-custom-dropdown/ul</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sharq Almadenah - Jubail - Sary'])[3]/following::ul[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EN'])[2]/following::ul[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul/div/app-custom-dropdown/ul</value>
   </webElementXpaths>
</WebElementEntity>
