<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ItemCheckbox</name>
   <tag></tag>
   <elementGuidId>4d182bc7-3003-4a1e-93f1-32c24fd6e623</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='checkbox'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.shipment-wrapper.ng-star-inserted > div.table-row > div.table-cell.small > input.sary-checkbox</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sary-checkbox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/div[@class=&quot;app-container rtl&quot;]/div[@class=&quot;app&quot;]/app-create-payment-request[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;page-content rtl&quot;]/div[@class=&quot;create-payment-request-wrapper mt-3&quot;]/div[@class=&quot;flex-grow-1 py-3 px-2 content-box sary-box-shadow&quot;]/div[@class=&quot;sary-pr-table d-flex flex-column h-100 ng-star-inserted&quot;]/div[@class=&quot;table-body overflow-y-auto flex-grow-1&quot;]/div[@class=&quot;shipment-wrapper ng-star-inserted&quot;]/div[@class=&quot;table-row&quot;]/div[@class=&quot;table-cell small&quot;]/input[@class=&quot;sary-checkbox&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='checkbox'])[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
   </webElementXpaths>
</WebElementEntity>
