<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>UploadFile</name>
   <tag></tag>
   <elementGuidId>c2155c42-6f8c-4918-8a0d-b853d4dcdcc1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.fa.fa-cloud-upload.mb-3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-cloud-upload mb-3</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/div[@class=&quot;app-container rtl&quot;]/div[@class=&quot;app&quot;]/app-create-payment-request[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;page-content rtl&quot;]/form[@class=&quot;w-100 ng-pristine ng-valid ng-touched&quot;]/div[@class=&quot;bill-info-wrapper d-flex my-3&quot;]/div[@class=&quot;bill content-box p-3 sary-box-shadow&quot;]/app-multipe-file-upload[1]/div[@class=&quot;multiple-file-upload-wrapper&quot;]/div[@class=&quot;file-input-wrapper&quot;]/label[@class=&quot;file-representation ng-star-inserted&quot;]/span[@class=&quot;fa fa-cloud-upload mb-3&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/span</value>
   </webElementXpaths>
</WebElementEntity>
